export * from './adminEndpoint.service';
import { AdminEndpointService } from './adminEndpoint.service';
export * from './customHealthEndpoint.service';
import { CustomHealthEndpointService } from './customHealthEndpoint.service';
export * from './department.service';
import { DepartmentService } from './department.service';
export * from './loginEndpoint.service';
import { LoginEndpointService } from './loginEndpoint.service';
export * from './messageEndpoint.service';
import { MessageEndpointService } from './messageEndpoint.service';
export const APIS = [AdminEndpointService, CustomHealthEndpointService, DepartmentService, LoginEndpointService, MessageEndpointService];
