export * from './adminEndpoint.service';
import { AdminEndpointService } from './adminEndpoint.service';
export * from './customHealthEndpoint.service';
import { CustomHealthEndpointService } from './customHealthEndpoint.service';
export * from './department.service';
import { DepartmentService } from './department.service';
export * from './loginEndpoint.service';
import { LoginEndpointService } from './loginEndpoint.service';
export * from './registrationEndpoint.service';
import { RegistrationEndpointService } from './registrationEndpoint.service';
export * from './userEndpoint.service';
import { UserEndpointService } from './userEndpoint.service';
export * from './vacationRequestEndpoint.service';
import { VacationRequestEndpointService } from './vacationRequestEndpoint.service';
export const APIS = [AdminEndpointService, CustomHealthEndpointService, DepartmentService, LoginEndpointService, RegistrationEndpointService, UserEndpointService, VacationRequestEndpointService];
