/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddShiftBlueprintDto } from './addShiftBlueprintDto';


export interface AddShiftToPlanBlueprintDto { 
    planId?: number;
    shifts?: Array<AddShiftBlueprintDto>;
}

