/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateShiftWeekBlueprintDto } from './createShiftWeekBlueprintDto';


export interface CreateShiftBlueprintDto { 
    description?: string;
    manPower?: number;
    shiftWeeks: Array<CreateShiftWeekBlueprintDto>;
}

