/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateShiftBlueprintDto } from './createShiftBlueprintDto';


export interface CreatePlanBlueprintDto { 
    description?: string;
    shifts?: Array<CreateShiftBlueprintDto>;
}

