/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Details of a day in the shift plan calendar
 */
export interface Day { 
    /**
     * Start of the day
     */
    start?: string;
    /**
     * End of the day
     */
    end?: string;
}

