/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduledShift } from './scheduledShift';


/**
 * Response for department shift plan calendar
 */
export interface DepartmentShiftplanCalendarResponse { 
    shifts?: Array<ScheduledShift>;
}

