/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Response for shift plan blueprint
 */
export interface PlanBlueprintResponse { 
    /**
     * Name of  department
     */
    department?: any;
    /**
     * List of shifts
     */
    shifts?: any;
}