/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShiftResponseDto } from './shiftResponseDto';


/**
 * Response for shift plan blueprint
 */
export interface PlanBlueprintResponse { 
    /**
     * ID of the plan blueprint
     */
    id?: number;
    /**
     * Description of the plan blueprint
     */
    description?: string;
    /**
     * Name of  department
     */
    department?: string;
    /**
     * List of shifts
     */
    shifts?: Array<ShiftResponseDto>;
}

