/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Scheduled shift response
 */
export interface ScheduledShiftResponseDto { 
    /**
     * Calendar week of the shift
     */
    calendarWeek?: number;
    /**
     * Year of the shift
     */
    year?: number;
    /**
     * Description of the shift
     */
    shiftDescription?: string;
    /**
     * Start date of the week
     */
    weekStartDate?: string;
}

