/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Day } from './day';


/**
 * Scheduled shift details
 */
export interface ScheduledShift { 
    shiftDescription?: string;
    day?: Day;
    /**
     * List of workers(email and name) assigned to the shift
     */
    workers?: Array<string>;
}

