/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShiftDayDetailDto } from './shiftDayDetailDto';


export interface ScheduledShiftDetailDto { 
    shiftDescription?: string;
    weekStart?: string;
    days?: Array<ShiftDayDetailDto>;
}

