/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Scheduled shift response
 */
export interface ScheduledShiftResponseDto { 
    /**
     * Calendar week of the shift
     */
    calendarWeek?: any;
    /**
     * Year of the shift
     */
    year?: any;
    /**
     * Description of the shift
     */
    shiftDescription?: any;
    /**
     * Start date of the week
     */
    weekStartDate?: any;
}