/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Response for shift plan blueprint
 */
export interface ShiftResponseDto { 
    /**
     * Name of the department
     */
    description?: any;
    /**
     * Number of employees needed for the shift
     */
    manPower?: any;
    /**
     * List of shift weeks
     */
    shiftWeeks?: any;
}