/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShiftWeekResponseDto } from './shiftWeekResponseDto';


/**
 * Response for shift plan blueprint
 */
export interface ShiftResponseDto { 
    /**
     * Name of the department
     */
    description?: string;
    /**
     * Number of employees needed for the shift
     */
    manPower?: number;
    /**
     * List of shift weeks
     */
    shiftWeeks?: Array<ShiftWeekResponseDto>;
}

