/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Shift day response
 */
export interface ShiftDayResponseDto { 
    /**
     * Day of the week
     */
    day?: ShiftDayResponseDto.DayEnum;
    /**
     * Start time of the shift
     */
    startTime?: string;
    /**
     * Duration of the shift
     */
    duration?: string;
}
export namespace ShiftDayResponseDto {
    export const DayEnum = {
        Monday: 'MONDAY',
        Tuesday: 'TUESDAY',
        Wednesday: 'WEDNESDAY',
        Thursday: 'THURSDAY',
        Friday: 'FRIDAY',
        Saturday: 'SATURDAY',
        Sunday: 'SUNDAY'
    } as const;
    export type DayEnum = typeof DayEnum[keyof typeof DayEnum];
}


