/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShiftWeekCreateDto } from './shiftWeekCreateDto';


export interface ShiftCreateDto { 
    description?: string;
    manPower?: number;
    shiftWeeks: Array<ShiftWeekCreateDto>;
}

