/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShiftDayDetailDto { 
    day?: ShiftDayDetailDto.DayEnum;
    startTime?: string;
    duration?: string;
    assignedUsers?: Array<string>;
}
export namespace ShiftDayDetailDto {
    export const DayEnum = {
        Monday: 'MONDAY',
        Tuesday: 'TUESDAY',
        Wednesday: 'WEDNESDAY',
        Thursday: 'THURSDAY',
        Friday: 'FRIDAY',
        Saturday: 'SATURDAY',
        Sunday: 'SUNDAY'
    } as const;
    export type DayEnum = typeof DayEnum[keyof typeof DayEnum];
}


