/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShiftDayCreateDto } from './shiftDayCreateDto';


export interface ShiftWeekCreateDto { 
    shiftDays: Array<ShiftDayCreateDto>;
}

