/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShiftDayResponseDto } from './shiftDayResponseDto';


/**
 * Response for a week of shifts
 */
export interface ShiftWeekResponseDto { 
    /**
     * List of shift day blueprints
     */
    shiftDays?: Array<ShiftDayResponseDto>;
}

