/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Shift day response
 */
export interface ShiftDayResponseDto { 
    /**
     * Day of the week
     */
    day?: any;
    /**
     * Start time of the shift
     */
    startTime?: any;
    /**
     * Duration of the shift
     */
    duration?: any;
}