/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileRestDto { 
    firstName?: string;
    lastName?: string;
    email: string;
    role?: string;
    department?: string;
}

